[build]

  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "https://dktweboptimisation.netlify.app/*"
  to = "https://dantekellman.co.uk/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://dantekellman.co.uk/*"
  to = "https://dantekellman.co.uk/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.dantekellman.co.uk/*"
  to = "https://dantekellman.co.uk/:splat"
  status = 301
  force = true